// Generated by CoffeeScript 1.6.2
(function() {
  var EventSchema, ObjectId, Schema, mongoose;

  mongoose = require('mongoose');

  Schema = mongoose.Schema;

  ObjectId = Schema.Types.ObjectId;

  EventSchema = new Schema({
    time: {
      type: Date,
      required: true
    },
    eventName: {
      type: String,
      required: true
    },
    user: ObjectId,
    object: ObjectId,
    objectType: String,
    container: ObjectId,
    containerId: String
  }, {
    strict: false
  });

  module.exports = function(connectionStr) {
    var Event, conn;

    conn = mongoose.createConnection(connectionStr);
    Event = conn.model('Event', EventSchema);
    return {
      Event: Event
    };
  };

}).call(this);
